version: "3.9"
services:
  # web:
  #   network_mode: host
  #   build: web-projetISEN
  #   container_name: dish-web
  #   ports:
  #     - "8080:8080"

  api:
    build: projetisenapi
    container_name: dish-api
    ports:
      - "8081:8080"
    volumes:
      - /srv/projetisenapi:/srv/projetisenapi
