version: "3.9"
services:
  api:
    build: projetisenapi
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/dish/projetisen-dd64c-firebase-adminsdk-d0aq1-b3f1a453eb.json
    container_name: dish-api
    volumes:
      - /srv/dish:/srv/dish
    ports:
      - "8082:8080"
  web:
    build: web-projetISEN
    container_name: dish-web
    ports:
      - "80:80"

