# Build stage
FROM openjdk:17-alpine as build
WORKDIR /app
COPY . .
RUN ./gradlew --no-daemon openApiGenerate
RUN ./gradlew --no-daemon war

# Deploy stage
FROM tomcat:9.0.68-jre17 as deploy
COPY --from=build /app/build/libs/projetisenapi.war /usr/local/tomcat/webapps/projetisenapi.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
